// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvXY3hMlAJ5RIHOE99fYRW__ttEiatoMQ',
    appId: '1:793366174938:web:dad8e06433ea7ec92599e3',
    messagingSenderId: '793366174938',
    projectId: 'ujikom-tsa-88e44',
    authDomain: 'ujikom-tsa-88e44.firebaseapp.com',
    databaseURL: 'https://ujikom-tsa-88e44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ujikom-tsa-88e44.appspot.com',
    measurementId: 'G-QMBPQBD834',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2HWdRJrV1UIjP-Qw-ceKutKDT3lzoX04',
    appId: '1:793366174938:android:d3174c8cce1989042599e3',
    messagingSenderId: '793366174938',
    projectId: 'ujikom-tsa-88e44',
    databaseURL: 'https://ujikom-tsa-88e44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ujikom-tsa-88e44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO1H44PaBZvop82mlyzV5SIinNUXw7Wpk',
    appId: '1:793366174938:ios:fd929ae9e7232cda2599e3',
    messagingSenderId: '793366174938',
    projectId: 'ujikom-tsa-88e44',
    databaseURL: 'https://ujikom-tsa-88e44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ujikom-tsa-88e44.appspot.com',
    iosClientId: '793366174938-e432rtitdb4je28ouna3793v7kglju1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ujikomTsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO1H44PaBZvop82mlyzV5SIinNUXw7Wpk',
    appId: '1:793366174938:ios:fd929ae9e7232cda2599e3',
    messagingSenderId: '793366174938',
    projectId: 'ujikom-tsa-88e44',
    databaseURL: 'https://ujikom-tsa-88e44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ujikom-tsa-88e44.appspot.com',
    iosClientId: '793366174938-e432rtitdb4je28ouna3793v7kglju1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ujikomTsa',
  );
}
